name: docs

on:
  # 每当 push 到 main 分支时触发部署
  push:
    branches: [main]
  # 手动触发部署
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - name: Swith gh-pages Branch
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          fetch-depth: 0
      - name: Get Current CNAME
        if: hashFiles('CNAME') != ''
        run: echo "::set-output name=content::$(cat CNAME)"
        id: cname
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          fetch-depth: 0
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14"

      - name: Cache dependencies
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn --frozen-lockfile

      - name: Build VuePress site
        run: yarn docs:build

      - name: Create CNAME file
        if: steps.cname.outputs.content
        uses: finnp/create-file-action@master
        env:
          FILE_NAME: "docs/.vuepress/dist/CNAME"
          FILE_DATA: "${{ steps.cname.outputs.content }}"

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: docs/.vuepress/dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
